name: Upload Package on Release
permissions:
  contents: write

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

on:
  release:
    types: [published]

jobs:
  tag:
    name: Upload New Release
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
          persist-credentials: false

      - name: Set up PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2.36.0
        with:
          php-version: "8.3"
          coverage: none
          tools: composer:v2

      - name: Install Composer dependencies
        uses: ramsey/composer-install@3cf229dc2919194e9e36783941438d17239e8520 # v3.1.1

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v5.0.0
        with:
          cache: "npm"
          node-version-file: ".nvmrc"

      - name: Install NPM dependencies
        run: npm ci
        env:
          CI: true

      - name: Create Artifact
        run: |
          npm run plugin-zip

      - name: Upload artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: universal-openai-connector
          path: universal-openai-connector.zip

      - name: Upload release asset
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          files: universal-openai-connector.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
